# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please set a name for this beer.', max_length=255, verbose_name='Name')),
                ('abv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcohol by volume')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Yellow'), (2, 'Amber'), (3, 'Brown'), (4, 'Black')], default=1, verbose_name='Color')),
                ('is_filtered', models.BooleanField(default=False, verbose_name='Is filtered?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beers',
            },
        ),
    ]
