# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Bar',
                'verbose_name_plural': 'Bar',
            },
        ),
    ]
